data:
  dataset_folder: data
  train_dataset: train.csv
  val_dataset: dev.csv
  test_dataset: test.csv

tokenizer:
  padding: max_length
  max_length: 256
  truncation: True
  return_attention_mask: True
  return_token_type_ids: True

text_embedding:
  type: pretrained #usual or pretrained
  text_encoder: vinai/phobert-base
  freeze: False
  d_features: 768
  d_model: 512
  dropout: 0.2

model:
  type_model: baseline
  intermediate_dims: 512
  dropout: 0.2

train:
  output_dir: checkpoint
  seed: 12345
  num_train_epochs: 10
  patience: 3
  learning_rate: 3.0e-5
  weight_decay: 0.
  metric_for_best_model: f1
  per_device_train_batch_size: 32
  per_device_valid_batch_size: 32

inference:
  with_label: True
  test_dataset: data/test.csv
  batch_size: 128

